### ISSUE TITLE
[Suggestion] Hidden food groups

### ISSUE THREAD

**Issue by Crowfooted** [WesCook/Nutrition#118] opened 2018-10-04 10:49 UTC
Food groups that do not display, either in the tooltip on food items or in the Nutrition graph screen, so that placeholder nutrients can be added to give specific food items effects without cluttering the interface.

Would work well in combination with [this suggested feature](https://github.com/WesCook/Nutrition/issues/117).

**Comment by WesCook** [comment] 2018-10-04 18:48
This sounds like a dupe of #109.  Does that cover the same use case?

**Comment by WesCook** [comment] 2018-10-16 10:34
Closed due to lack of a response.

**Closed as completed by WesCook** 2018-10-16 10:34 UTC
Labels: duplicate

**Comment by WesCook** [comment] 2018-10-22 23:24
Just a heads up, this feature was added in the release of [v4.0.0](https://github.com/WesCook/Nutrition/releases/tag/v4.0.0).
