### ISSUE TITLE
Changing the food value does not affect the nutrient value

### ISSUE THREAD

**Issue by GrigoryiAI** [WesCook/Nutrition#260] opened 2024-01-24 14:35 UTC
The thing is that the mod set the nutrient value in accordance with the food value. And it does it as I understand by taking food values from other mods (that we can add through json), but further changes in the food value through the configs or scripts of other mods do not affect the nutrient value, it remains what was originally written in the mods, sometimes very unbalanced(at the same time, I have food that replenishes half a shank of hunger and 4% of nutrient and anither food that replenishes 3 full shanks and 4% of nutrient). So my question, is there a way that I can make nutrition mod calculate current food values after all config changes from other mods applies? Or maybe there is a way to config food values before this mod calculates nutrition?
I can't fully understand how the item.getHealAmount method from calculateNutrition works, it seems to ignore configs from other mods that change food value and FoodTweaker scripts. I don't know what other options I have other than creating fork, but it will take a lot of time because I'm not very familiar with programming. 
Also pam's harvestcraft mod works with the nutrition mod as I expect. When I change vanilla food stats through their config, the nutrition mod can detect it and change the nutrient value accordingly. Can I make this kind of compatibility with other mods by any ways? 
Would appreciate any answer and any tips.

**Comment by WesCook** [comment] 2024-01-24 17:19
Hi Grigory,

Nutrition gets the food value through `ItemFood#getHealAmount`, like you noticed.  This is just a Minecraft function that reads the value directly.  If mods are customizing the actual heal amount that the game registers, then Nutrition will be able to read that properly.  If they're intercepting the call and then modifying it on the fly, then Nutrition won't know about it.

I've not used FoodTweaker, but it's my assumption that they're using the latter method.  That makes sense for a Tweaker mod since they support features like runtime changes.

Unfortunately this isn't so much a "bug" as it is by design, which means it's not likely to be changed to improve compatibility.  Nutrition is also largely in maintenance mode now, and going off the commit history I assume the same is true of FoodTweaker. 
 Though perhaps @Mrbysco could weigh in there.

For myself, I'm unlikely to get Forge set up and start relearning the codebase unless there were a major bug, so I'm afraid I can't offer any fixes on my end.  I will say that Nutrition is MIT though if you wish to fork the mod to make that change.  I would just ask that you give your fork a different name, especially if hosting on popular mod hosting websites.

I'll go ahead and close this issue since it's not something I can action.  Best of luck in finding a solution though.

**Closed as not planned** 2024-01-24 17:20 UTC
Labels: wontfix
