### ISSUE TITLE
GUI Bars not accurate with multiple players on server

### ISSUE THREAD

**Issue by michaelburns710** [WesCook/Nutrition#202] opened 2020-02-02 20:38 UTC
I'm wondering if this is an issue with the modpack or the mod itself. Playing on Enigmatica 2. No matter what the percentage is the bars stay around 80%.

**Comment by michaelburns710** [comment] 2020-02-02 20:40
Could only duplicate issue on twitch launcher. MultiMC with same modpack was fine.

**Comment by WesCook** [comment] 2020-02-03 19:49
If the mod has a bug that's specific to one launcher, that could still be a problem.  It does however seem unlikely that's what caused it.

When you experienced the bug on the Twitch launcher, were you playing on a server?  And on MultiMC were you playing in singleplayer?  Were there any other differences that might have accounted for this discrepancy?

I ask because I've been trying to narrow down a bug which sounds similar, and I'd like to learn all I can about it.

**Comment by michaelburns710** [comment] 2020-02-03 21:45
I may have jumped the gun on limiting it to one launcher. I have 4 people
including myself playing on a Server. One of us doesnt have the bug ( he
can only use multimc for some reason) and the rest have the bug on both
launchers. I have no tried single player but will this afternoon and report
findings. Please let me know anything else you may need.

**Comment by WesCook** [comment] 2020-02-03 21:50
Thanks, that's a useful data point.  Another useful test may be to see if the bug occurs when only one player is on the server.  The related bug I've been tracking only occurs when multiple players are on a server.

I should also mention that in my bug, the effects are applied correctly.  The bug is only visual.  The bar shows the correct position at first, then jumps to a predefined amount.  If that's similar to what you're seeing, let me know!

**Comment by michaelburns710** [comment] 2020-02-03 22:07
That is exactly what we are seeing, and I was only able to get his input on
the issue when he was the only player on the server so that makes sense

**Comment by WesCook** [comment] 2020-02-03 22:41
Okay, it looks like we're talking about the same bug then.  I'd only seen it present in Seablock: Rustic Waters before, but it's good to know it's happening in Enigmatica 2 as well.  Is it regular Enigmatica, or Expert or Skyblock?

I think this issue started presenting some time after the 4.0 refactor.  It isn't showing up in my dev environment so it may be a conflict with another mod, or some other factor.

I'm going to re-open this issue as this needs to be fixed before closing off the 1.12 branch.  Thanks for the report, and if you come up with any other details I'd be glad to hear them.

**Comment by michaelburns710** [comment] 2020-02-03 22:54
This is Expert. Have not tried on the other versions. But it might be worth
investigating on the standard version too. Ill boot up a server later with
the standard Enigmatica 2

**Comment by condac** [comment] 2020-02-09 11:59
I play ATM3 and ATM3 remix with MultiMC launcher. This bug have been there for as long as this mod have been included. I have a dedicated server that I connect to so I play in Multiplayer. 
When I open the nutritions bars they are correct for one frame and then they render at 75%. So if you open and close gui fast you can see they render correct for a small time. 
 I was surprised that this bug was only reported 1 week ago, have been like this for a long time.

**Closed as completed** 2020-02-12 18:12 UTC
Labels: bug

**Comment by WesCook** [comment] 2020-02-12 18:27
I tracked this issue down to a conflict with JourneyMap.  It seems their radar system was rapidly creating instances of `EntityOtherPlayerMP` which was firing the event `AttachCapabilitiesEvent<Entity>`.

I use that event on the client to initially set the player's local nutrition.  The assumption was that it would only fire once when the player joins the server (thus setting their nutrition to the default).  But all these instances of `EntityOtherPlayerMP` were also being detected and causing the local nutrition to reset.

The flashing change was caused by a nutrition update I request when the GUI is opened.  It briefly set the bar to the correct number, then reverted back down to the wrong value.  Because labels are created when the GUI is initialized, they didn't update and retained their correct value.  Only the bars render each tick and were affected.

I had a chat with Mysticdrew and we came up with a fix on both ends.  I'll be deploying a new build to fix this shortly, and he'll be releasing a fix for JM which will improve their radar logic.  Either fix should solve the problem, but you might as well get both.

Thanks all for providing any details on this issue.  It was a tricky one to track down.

edit: [Nutrition v4.5.0](https://github.com/WesCook/Nutrition/releases/tag/v4.5.0) and [journeymap-1.12.2-5.5.9](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/2880387) can be downloaded now.
