### ISSUE TITLE
[Update suggestion] HarvestCraft

### ISSUE THREAD

**Issue by irongrid** [WesCook/Nutrition#165] opened 2019-05-14 18:31 UTC
Hey, could it be possible to update Pam's Harvestcrafts newest crops and foods in this mod? 
https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2696248

**Comment by WesCook** [comment] 2019-05-14 23:26
Thanks for the suggestion.  This one is on the list, but hasn't been finished yet.  I've been focusing on real life stuff recently.  I'll include this in the next update, or if somebody submits a pull request I'll merge it in sooner.

I'm going to close this as a duplicate of #160 though as that issue includes some additional details.  Thanks again!

**Closed as completed by WesCook** 2019-05-14 23:26 UTC
Labels: duplicate
