### ISSUE TITLE
Have Toughness go to Level 4/5 instead of resetting back down to 1

### ISSUE THREAD

**Issue by Vyraal1** [WesCook/Nutrition#53] opened 2018-02-28 15:47 UTC
Ingame after getting a certain amount of Nutrition in all 5 categories, the toughness buff that adds hearts resets back down to just plain old Toughness. Minor issue, but it does seem a bit unintuitive.

**Comment by WesCook** [comment] 2018-02-28 15:53
Is the Toughness level actually resetting, or just the label in the effects screen?  I'm pretty sure that's just now Minecraft handles high-levels on potion effects; it removes the number altogether.

**Comment by Vyraal1** [comment] 2018-02-28 19:39
Hey thanks for the quick response. It's just the label appanretly, after some digging around another modder mentioned that this is potentially a localization problem. and that localizing in a lang file could fix it like here: https://github.com/strikerrocker/VanillaTweaks/blob/e4656c4871bddf505eff87004d9419522ae0e49e/src/main/resources/assets/vt/lang/en_us.lang#L300

Modpack devs can localize it themselves, but since you're one of the very few mods devs that have a potion potency go up to 5 that I'm aware of, I figured it might be appropriate request this.

**Comment by WesCook** [comment] 2018-02-28 22:34
Thanks for doing the research on that.  I did a bit of testing, but found I actually wasn't able to set the localization for `potion.potency.4` using that method.  I'm not sure why, as both VanillaTweaks and Astral Sorcery simply set the key in the lang file.

Ultimately though I was a bit hesitant to set a vanilla-specific key anyway, so I'm not too upset that it didn't work.  I am sorry for the confusion caused by level 5+ potion effects though.

If it's really bugging you, you could probably override it with [Resource Loader](https://minecraft.curseforge.com/projects/resource-loader).  I've used that mod successfully to override lang keys before.

I'm actually glad you drew my attention to the localization files though as it made me realize I was still using the v2 format.  I've updated them to the v3 format now.

I'm going to close this one as "invalid" because it's technically a Minecraft bug, but I appreciate you making me aware of the cause and a potential solution.  Great report!

**Closed as completed** 2018-02-28 22:34 UTC
Labels: invalid
