### ISSUE TITLE
[SUGGESTION] Culinary Construct support 

### ISSUE THREAD

**Issue by DMNerd** [WesCook/Nutrition#187] opened 2019-10-21 00:37 UTC
It would be awesome to see support for this mod, it brings TFC style sandwich crafting (TFC had salads AFAIK)

https://www.curseforge.com/minecraft/mc-mods/culinary-construct

**Comment by WesCook** [comment] 2019-10-21 00:50
Thanks for the suggestion, but it's a duplicate of #185.

**Closed as completed** 2019-10-21 00:51 UTC
Labels: duplicate
